# Generated by Django 2.2.6 on 2019-10-09 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_question_hint'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='questions_answered',
            field=models.ManyToManyField(to='home.Question'),
        ),
    ]
