# Generated by Django 2.2.6 on 2019-10-14 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_questions_answered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='questions_answered',
            field=models.ManyToManyField(default=3, to='home.Question'),
        ),
    ]
