# Generated by Django 2.2.6 on 2019-10-16 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20191014_0115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='questions_answered',
            field=models.ManyToManyField(to='home.Question'),
        ),
    ]
