# Generated by Django 2.2.6 on 2019-10-16 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20191016_0128'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='correctAnswers',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='wrongAnswers',
            field=models.IntegerField(default=0),
        ),
    ]
