# Generated by Django 2.2.6 on 2019-10-18 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20191016_0224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='questions_answered',
        ),
    ]
