# Generated by Django 2.2.6 on 2019-11-06 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_teammember'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Default Title', max_length=20)),
                ('description', models.CharField(default='Default Description', max_length=1000)),
                ('link', models.CharField(default='Default Description', max_length=1000)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='teammember',
            name='description',
            field=models.CharField(default='Default Description', max_length=1000),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='title',
            field=models.CharField(default='Default Title', max_length=20),
        ),
    ]
