# Generated by Django 2.2.6 on 2019-11-06 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20191106_0659'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testdescription',
            name='description',
        ),
        migrations.AddField(
            model_name='testdescription',
            name='blurb_1',
            field=models.CharField(default='Default Description', max_length=1000),
        ),
        migrations.AddField(
            model_name='testdescription',
            name='blurb_2',
            field=models.CharField(default='Default Description', max_length=1000),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='description',
            field=models.CharField(default='Default Description', max_length=100),
        ),
    ]
