# Generated by Django 2.2.6 on 2019-11-06 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20191106_0700'),
    ]

    operations = [
        migrations.AddField(
            model_name='testdescription',
            name='test_type',
            field=models.CharField(choices=[('ACT', 'ACT'), ('SAT', 'SAT'), ('GRE', 'GRE')], default='SAT', max_length=3),
        ),
        migrations.AlterField(
            model_name='testdescription',
            name='link',
            field=models.CharField(default='Default Link', max_length=1000),
        ),
    ]
