# Generated by Django 2.2.6 on 2019-10-18 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Practice_Test', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='question',
            name='quiz',
        ),
        migrations.RemoveField(
            model_name='questionattempt',
            name='attempt',
        ),
        migrations.RemoveField(
            model_name='questionattempt',
            name='question',
        ),
        migrations.RemoveField(
            model_name='questionattempt',
            name='response',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='quizattempt',
            name='quiz',
        ),
        migrations.RemoveField(
            model_name='quizattempt',
            name='student',
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='QuestionAttempt',
        ),
        migrations.DeleteModel(
            name='Quiz',
        ),
        migrations.DeleteModel(
            name='QuizAttempt',
        ),
    ]
