# Generated by Django 2.2.6 on 2019-10-07 20:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('date_answered', models.DateTimeField(default=django.utils.timezone.now)),
                ('subject', models.TextField()),
                ('answer_index', models.IntegerField()),
                ('image', models.ImageField(default=None, upload_to='question_images')),
            ],
        ),
    ]
