# Generated by Django 2.2.6 on 2019-10-08 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20191008_0017'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='hint',
            field=models.TextField(default='There is no hint for this Question'),
        ),
    ]
