# Generated by Django 2.2.6 on 2019-10-09 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20191009_2253'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='date_answered',
            new_name='date_published',
        ),
    ]
