# Generated by Django 2.2.6 on 2019-10-18 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20191016_0142'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='questionId',
            field=models.IntegerField(default=1),
        ),
    ]
