# Generated by Django 2.2.6 on 2019-10-18 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_question_questionid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='questionId',
            field=models.IntegerField(default=0),
        ),
    ]
