# Generated by Django 2.2.6 on 2019-10-18 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20191018_0304'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='orderId',
            field=models.IntegerField(default=0),
        ),
    ]
