# Generated by Django 2.2.6 on 2019-10-18 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_question_orderid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='questionId',
        ),
        migrations.AddField(
            model_name='question',
            name='copyId',
            field=models.IntegerField(default=0),
        ),
    ]
