# Generated by Django 2.2.6 on 2019-10-18 21:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_profile_questions_answered'),
        ('home', '0014_auto_20191018_2028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='copyId',
        ),
        migrations.CreateModel(
            name='QuestionCopy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('prompt', models.TextField()),
                ('image', models.ImageField(default=None, upload_to='question_images')),
                ('date_published', models.DateTimeField(default=django.utils.timezone.now)),
                ('hint', models.TextField(default='There is no hint for this Question')),
                ('copyId', models.IntegerField(default=0)),
                ('originalOrderId', models.IntegerField(default=0)),
                ('userAnswer', models.IntegerField(default=0)),
                ('answeredCorrectly', models.BooleanField(default=False)),
                ('profile', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='questions_answered', to='users.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='ChoiceCopy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=200)),
                ('correct', models.BooleanField(default=False)),
                ('questionCopy', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='home.QuestionCopy')),
            ],
        ),
    ]
