# Generated by Django 2.2.6 on 2019-10-18 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_auto_20191018_2105'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choicecopy',
            old_name='questionCopy',
            new_name='question',
        ),
    ]
