# Generated by Django 2.2.6 on 2019-10-19 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_auto_20191019_0030'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='test_type',
            field=models.CharField(choices=[('ACT', 'ACT'), ('SAT', 'SAT'), ('GRE', 'GRE')], default='SAT', max_length=3),
        ),
        migrations.AddField(
            model_name='questioncopy',
            name='test_type',
            field=models.CharField(choices=[('ACT', 'ACT'), ('SAT', 'SAT'), ('GRE', 'GRE')], default='SAT', max_length=3),
        ),
    ]
