# Generated by Django 2.2.6 on 2019-10-24 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_auto_20191019_2133'),
    ]

    operations = [
        migrations.CreateModel(
            name='ACTQuestion',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('home.question',),
        ),
        migrations.CreateModel(
            name='GREQuestion',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('home.question',),
        ),
        migrations.CreateModel(
            name='SATQuestion',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('home.question',),
        ),
        migrations.AddField(
            model_name='questioncopy',
            name='currentUserAccuracy',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='questioncopy',
            name='numberCorrectOfType',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='questioncopy',
            name='numberWrongOfType',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='question',
            name='subject',
            field=models.CharField(choices=[('Reading', 'Reading'), ('Math', 'Math'), ('Science', 'Science')], default='Math', max_length=7),
        ),
        migrations.AlterField(
            model_name='questioncopy',
            name='subject',
            field=models.CharField(choices=[('Reading', 'Reading'), ('Math', 'Math'), ('Science', 'Science')], default='Math', max_length=7),
        ),
    ]
