# Generated by Django 2.2.6 on 2019-10-28 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_auto_20191027_2355'),
    ]

    operations = [
        migrations.AddField(
            model_name='questioncopy',
            name='currentGeneralAccuracy',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='questioncopy',
            name='numberCorrectGeneral',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='questioncopy',
            name='numberWrongGeneral',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='question',
            name='subject',
            field=models.CharField(choices=[('Reading', 'Reading'), ('Science', 'Science'), ('Math', 'Math')], default='Math', max_length=7),
        ),
        migrations.AlterField(
            model_name='questioncopy',
            name='subject',
            field=models.CharField(choices=[('Reading', 'Reading'), ('Science', 'Science'), ('Math', 'Math')], default='Math', max_length=7),
        ),
    ]
