# Generated by Django 2.2.6 on 2019-11-06 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_auto_20191028_0039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='subject',
            field=models.CharField(choices=[('Science', 'Science'), ('Math', 'Math'), ('Reading', 'Reading')], default='Math', max_length=7),
        ),
        migrations.AlterField(
            model_name='questioncopy',
            name='subject',
            field=models.CharField(choices=[('Science', 'Science'), ('Math', 'Math'), ('Reading', 'Reading')], default='Math', max_length=7),
        ),
    ]
