# Generated by Django 2.2.6 on 2019-11-06 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_auto_20191106_0711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='subject',
            field=models.CharField(choices=[('Math', 'Math'), ('Science', 'Science'), ('Reading', 'Reading')], default='Math', max_length=7),
        ),
        migrations.AlterField(
            model_name='questioncopy',
            name='subject',
            field=models.CharField(choices=[('Math', 'Math'), ('Science', 'Science'), ('Reading', 'Reading')], default='Math', max_length=7),
        ),
    ]
